name: Deploy Mainnet

on:
  push:
    branches:
      - mainnet

concurrency:
  group: 'mainnet'
  cancel-in-progress: true

jobs:
  mainnet-deploy:
    uses: ./.github/workflows/cloudflare-pages-deploy.yml
    with:
      environment: mainnet
      near_wallet_env: mainnet
    secrets: inherit
