name: Deploy Staging

on:
  push:
    branches:
      - master

concurrency:
  group: 'testnet'
  cancel-in-progress: true

jobs:
  testnet-staging-deploy:
    uses: ./.github/workflows/cloudflare-pages-deploy.yml
    with:
      environment: testnet-staging
      near_wallet_env: testnet_STAGING
    secrets: inherit

  mainnet-staging-deploy:
    uses: ./.github/workflows/cloudflare-pages-deploy.yml
    with:
      environment: mainnet-staging
      near_wallet_env: mainnet_STAGING
    secrets: inherit
